pipeline:
  buildjar:
    image: maven:3.2-jdk-8
    commands:
      - mvn -q package
  buildimage:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build
         --label org.label-schema.vcs-ref=$DRONE_COMMIT_SHA
         --label build-number=$DRONE_BUILD_NUMBER
         --label build-date="$(date)"
         -t devopsbootcamp2/devcamp_login:$DRONE_COMMIT_SHA .
  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker kill test || true
      - docker rm test || true
      - docker create --name test devopsbootcamp2/devcamp_login:$DRONE_COMMIT_SHA
      - docker cp ./test.sh test:/test.sh
      - docker start test /test.sh
  push:
    image: docker
    environment:
      - USER=${HUB_USER}
      - PASS=${HUB_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u $USER -p $PASS
      - docker tag devopsbootcamp2/devcamp_login:$DRONE_COMMIT_SHA devopsbootcamp2/devcamp_login:production
      - docker push devopsbootcamp2/devcamp_login:$DRONE_COMMIT_SHA
      - docker push devopsbootcamp2/devcamp_login:production
  deploy: 
    image: docker
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ssh $SSH_USER@$SSH_MANAGER /deploy_login.sh
  notify:
    when:
        status: [failure]
    image: amouat/network-utils
    commands: 
      - chmod +x ./notifyfailure.sh
      - ./notifyfailure.sh
  finish:
    image: debian
    commands: 
      - date

 